version: "3.8"

services:
  backend:
    container_name: my_backend_course
    image: backend
    build:
      context: ./
      dockerfile: backend.dockerfile
    ports:
      - 8383:8383
    environment:
      - .env

  db:
    container_name: db
    image: "postgres"
    restart: "always"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  pgdata:
    driver: local
